dependencies {
    modImplementation(libs.balmFabric) {
        changing = libs.versions.balm.get().endsWith("SNAPSHOT")
    }
    modCompileOnly "mezz.jei:jei-$jei_minecraft_version-common-api:$jei_version"
    if (jei_minecraft_version == minecraft_version) {
        modRuntimeOnly "mezz.jei:jei-$jei_minecraft_version-fabric:$jei_version"
    }
    modCompileOnly "curse.maven:jade-324717:$jade_fabric_version"
    modCompileOnly "curse.maven:fabricae-ex-nihilo-596911:5298550"
    // modRuntimeOnly("com.github.mattidragon:configtoolkit:1.0.0")
}