# Mod
version = 21.11.0
mod_id = excompressum
mod_name = Ex Compressum
mod_author = BlayTheNinth
credits = BlayTheNinth
description=Ex Nihilo Addon. Attempts to reduce grind by adding pre-automation tools like compressed hammers.
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/mc/ex-compressum
sources=https://github.com/TwelveIterations/ExCompressum
issues=https://github.com/TwelveIterations/ExCompressum/issues
discord = https://discord.gg/VAfZ2Nau6j
license=All Rights Reserved

# Publishing
curseforge_project_id = 241967
curseforge_environments = Client,Server
modrinth_project_id = mwfOGtr1
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Build
java_version = 21
neoforge_snapshot_url = 
include_fabric=true
include_neoforge=true
include_forge=true

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
