# Mod
version = 20.1.6
mod_id = excompressum
mod_name = Ex Compressum
mod_author = BlayTheNinth
credits = BlayTheNinth
license = All Rights Reserved
group = net.blay09.mods
pack_format_number = 18
description=Ex Nihilo Addon. Attempts to reduce grind by adding pre-automation tools like compressed hammers.
homepage=https://mods.twelveiterations.com/mc/ex-compressum
sources=https://github.com/TwelveIterationMods/ExCompressum
issues=https://github.com/TwelveIterationMods/ExCompressum/issues

# Publishing
release_type = release
curseforge_project_id = 241967
modrinth_project_id = mwfOGtr1

# Minecraft
minecraft_version = 1.20.1
minimum_minecraft_version = 1.20
minecraft_versions = 1.20,1.20.1
minecraft_version_range=[1.20,1.21)
java_version = 17

parchment_minecraft = 1.20.1
parchment_version = 2023.09.03

# Balm
balm_version = 7.4.0-SNAPSHOT
balm_version_range = [7.2.0,)

# Forge
forge_version = 47.2.20
forge_version_range=[46.0.0,)
forge_loader_version_range=[46,)
forge_mixins=true

# Fabric
fabric_version = 0.92.3+1.20.1
fabric_loader_version = 0.16.10

# Dependencies
jei_minecraft_version=1.20.1
jei_version=15.20.0.106
rei_version=10.0.581
jade_fabric_version=4160727
jade_forge_version=4159759
mixin_version=0.8.5
modmenu_version=7.2.2
theoneprobe_version=4159743
cloth_config_version=10.0.95
novacore_version=1.20.1-1.0.0-build.3
exnihilosequentia_version=1.20.1-5.0.0-build.6

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false