@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.excompressum.newregistry.heavysieve;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;