@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.excompressum.compat.exnihiloadscensio;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;