@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.excompressum.registry.chickenstick;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;