dependencies {
    implementation(libs.balmNeoForge) {
        changing = libs.versions.balm.get().endsWith("SNAPSHOT")
    }

    compileOnly("novamachina.novacore:novacore:1.21.4-4.0.0-build.5")
    compileOnly("novamachina.exnihilosequentia:exnihilosequentia:1.21.4-7.0.2-build.3")
    compileOnly("curse.maven:ex-deorum-901420:8096345")
}
