@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.excompressum.registry.heavysieve.newregistry;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;